### DISCUSSION TITLE
Plot arrays/multiarrays as graphs?

### DISCUSSION THREAD

**Discussion by lucasw** [facontidavide/PlotJuggler#608] [Ideas]
For example if a message is received with [0, 1, 2] in it, the current plot would have only those values plotted in a line left to right (assume a nominal point spacing for 1d data), and if a new message arrives with [3, 4, 5] the old graph would be completely replaced, there would be no message time history at all.

At the time of these questions it looks like the answer was no, but maybe this is possible now?

https://answers.ros.org/question/321890/visualize-or-plot-float32multiarray-data-field/
https://answers.ros.org/question/175151/rqt_plot-plot-2d-data/

**Comment by facontidavide** [comment]
With the new "Reactive Lua" function, you can do pretty much everything you want with your data.
To give more concrete suggestions, I probably need a more concrete example (I am not understanding exactly your data layout)

https://slides.com/davidefaconti/plotjuggler-reactive-scripts/fullscreen

**Reply by lucasw** [reply]
The lua scripting does look capable of it.

In this example I'm using `Float32MultiArray` as a 1D array, and plotting just the most recent array like this:

![multi_array_graph_rviz_plugin](https://user-images.githubusercontent.com/1334122/154498251-defdfaf2-f39b-4c64-9616-76092880ae46.png)

```
layout: 
  dim: []
  data_offset: 0
data: [1.9999999949504854e-06, 6.000000212225132e-06, 1.2000000424450263e-05, 1.9999999494757503e-05, 2.9999999242136255e-05, 4.199999966658652e-05, 5.6000000768108293e-05, 7.200000254670158e-05, 9.000000136438757e-05, 0.00011000000085914508, 0.0001340000017080456, 0.00016199999663513154, 0.0001939999929163605, 0.0002300000051036477, 0.0002699999895412475, 0.00031400000443682075, 0.00036199999158270657, 0.0004140000091865659, 0.00046999999904073775, 0.0005300000193528831, 0.0005939999828115106, 0.0006619999767281115, 0.0007340000011026859, 0.0008099999977275729, 0.0008900000248104334, 0.0009740000241436064, 0.001062000053934753, 0.001154000055976212, 0.0012499999720603228, 0.0013500000350177288, 0.0014400000218302011, 0.0015200000489130616, 0.0015899999998509884, 0.0016499999910593033, 0.0017000000225380063, 0.0017399999778717756, 0.001769999973475933, 0.0017900000093504786, 0.0017999999690800905, 0.0017999999690800905, 0.001791000016964972, 0.0017729999963194132, 0.0017460000235587358, 0.0017099999822676182, 0.001664999988861382, 0.0016110000433400273, 0.0015480000292882323, 0.001475999946705997, 0.001395000028423965, 0.0013050000416114926, 0.0012080000014975667, 0.001104000024497509, 0.0009929999941959977, 0.0008750000270083547, 0.000750000006519258, 0.0006179999909363687, 0.00047900000936351717, 0.0003330000035930425, 0.00018000000272877514, 1.9999999494757503e-05, -0.00014699999883305281, -0.0003209999995306134, -0.0005019999807700515, -0.0006900000153109431, -0.0008849999867379665, -0.0010870000114664435, -0.0012959999730810523, -0.0015119999879971147, -0.0017350000562146306, -0.0019650000613182783, -0.0022100000642240047, -0.002469999948516488, -0.002744999947026372, -0.0030350000597536564, -0.0033400000538676977, -0.003659999929368496, -0.003994999919086695, -0.00434499979019165, -0.00471000000834465, -0.005090000107884407]
```

It looks like there would need to be a for loop around getting the value of each element of the array
```
... for i in length of data
  series_x = TiimeseriesView.find("mobile_base/yaw_0/data.%d", index)
  -- append series_x.at(0) to list 
...
```

Or I could get it all in one call?
```
series_x = TiimeseriesView.find("mobile_base/yaw_0/data")
```
