### ISSUE TITLE
[ROS] Not consistent timestamp re-publish while playing a rosbag

### ISSUE THREAD

**Issue by tolomeis** [facontidavide/PlotJuggler#478]
Hi everyone! Since one of the last updates, I found a little annoying bug involving the playback of rosbag files.
## Problem description
When I tried to run the bag with the ROS re-publisher and the "Keep original timestamp" option, I found that the timestamps published to the /clock topic are not consistent in time. 
To be sure I echoed the `/clock` topic, which you can find here, and you can see (from the third timestamp) that in some instants the time published by PlotJuggler goes "back in time", which raises the "ROS time moved backwards exception" whenever a node calls a timer or a sleep function. 

```---
clock: 
  secs: 1621527114
  nsecs: 729352933
---
clock: 
  secs: 1621527114
  nsecs: 729416943
---
clock: 
  secs: 1621527114
  nsecs: 720763291
---
clock: 
  secs: 1621527114
  nsecs: 739353045
```
I tried with a simpler rosbag and I couldn't reproduce the error, so I think it comes from having two or more different topics with stamped messages at different rates, but I'm not sure.
## Steps to reproduce
I'm running Ubuntu 20.04 with ROS Noetic and PlotJuggler 3.2.0. Here is a screenshot with the settings from the re-publisher. 
I attached the rosbag that I used to reproduce the bug, but as I said I found that the error comes with every rosbag with multiple stamped topics.
 [testbag_min.zip](https://github.com/facontidavide/PlotJuggler/files/6763432/testbag_min.zip)
![Screenshot from 2021-07-05 12-16-25](https://user-images.githubusercontent.com/11806270/124458082-ddb94a80-dd8c-11eb-965b-331b1030cd0f.png)

I hope to be helpful, thank you!

**Comment by facontidavide** [comment]
Hi,

I am not sure I see the problem here. Publishing uses the motion of the slider at the bottom or the timetracker (vertical red line) to publish.

If you move it from the right to the left, you move back in time!

What would be wrong is if the PLAY button trigger this error, but this doesn't happen in my tests, but If I use PLAY, this is my output:

```
---
clock: 
  secs: 1621527114
  nsecs: 719434867
---
clock: 
  secs: 1621527114
  nsecs: 720763291
---
clock: 
  secs: 1621527114
  nsecs: 729352933
---
clock: 
  secs: 1621527114
  nsecs: 729416943
---
clock: 
  secs: 1621527114
  nsecs: 731022875
---
clock: 
  secs: 1621527114
  nsecs: 739353045
---
clock: 
  secs: 1621527114
  nsecs: 739391614
```
